export enum UnitedStatesRegions {
  WEST = 'West',
  MIDWEST = 'Midwest',
  NORTHEAST = 'Northeast',
  SOUTH = 'South',
}

// https://gist.github.com/meiqimichelle/7727723
export const UnitedStatesStateRegionMap = [
  {
    region: UnitedStatesRegions.WEST,
    state: 'Alaska',
    latitude: 61.385,
    longitude: -152.2683,
  },
  {
    region: UnitedStatesRegions.SOUTH,
    state: 'Alabama',
    latitude: 32.799,
    longitude: -86.8073,
  },
  {
    region: UnitedStatesRegions.SOUTH,
    state: 'Arkansas',
    latitude: 34.9513,
    longitude: -92.3809,
  },
  {
    region: UnitedStatesRegions.WEST,
    state: 'Arizona',
    latitude: 33.7712,
    longitude: -111.3877,
  },
  {
    region: UnitedStatesRegions.WEST,
    state: 'California',
    latitude: 36.17,
    longitude: -119.7462,
  },
  {
    region: UnitedStatesRegions.WEST,
    state: 'Colorado',
    latitude: 39.0646,
    longitude: -105.3272,
  },
  {
    region: UnitedStatesRegions.NORTHEAST,
    state: 'Connecticut',
    latitude: 41.5834,
    longitude: -72.7622,
  },
  {
    region: UnitedStatesRegions.SOUTH,
    state: 'Delaware',
    latitude: 39.3498,
    longitude: -75.5148,
  },
  {
    region: UnitedStatesRegions.SOUTH,
    state: 'Florida',
    latitude: 27.8333,
    longitude: -81.717,
  },
  {
    region: UnitedStatesRegions.SOUTH,
    state: 'Georgia',
    latitude: 32.9866,
    longitude: -83.6487,
  },
  {
    region: UnitedStatesRegions.WEST,
    state: 'Hawaii',
    latitude: 21.1098,
    longitude: -157.5311,
  },
  {
    region: UnitedStatesRegions.MIDWEST,
    state: 'Iowa',
    latitude: 42.0046,
    longitude: -93.214,
  },
  {
    region: UnitedStatesRegions.WEST,
    state: 'Idaho',
    latitude: 44.2394,
    longitude: -114.5103,
  },
  {
    region: UnitedStatesRegions.MIDWEST,
    state: 'Illinois',
    latitude: 40.3363,
    longitude: -89.0022,
  },
  {
    region: UnitedStatesRegions.MIDWEST,
    state: 'Indiana',
    latitude: 39.8647,
    longitude: -86.2604,
  },
  {
    region: UnitedStatesRegions.MIDWEST,
    state: 'Kansas',
    latitude: 38.5111,
    longitude: -96.8005,
  },
  {
    region: UnitedStatesRegions.SOUTH,
    state: 'Kentucky',
    latitude: 37.669,
    longitude: -84.6514,
  },
  {
    region: UnitedStatesRegions.SOUTH,
    state: 'Louisiana',
    latitude: 31.1801,
    longitude: -91.8749,
  },
  {
    region: UnitedStatesRegions.NORTHEAST,
    state: 'Massachusetts',
    latitude: 42.2373,
    longitude: -71.5314,
  },
  {
    region: UnitedStatesRegions.SOUTH,
    state: 'Maryland',
    latitude: 39.0724,
    longitude: -76.7902,
  },
  {
    region: UnitedStatesRegions.NORTHEAST,
    state: 'Maine',
    latitude: 44.6074,
    longitude: -69.3977,
  },
  {
    region: UnitedStatesRegions.MIDWEST,
    state: 'Michigan',
    latitude: 43.3504,
    longitude: -84.5603,
  },
  {
    region: UnitedStatesRegions.MIDWEST,
    state: 'Minnesota',
    latitude: 45.7326,
    longitude: -93.9196,
  },
  {
    region: UnitedStatesRegions.MIDWEST,
    state: 'Missouri',
    latitude: 38.4623,
    longitude: -92.302,
  },
  {
    region: UnitedStatesRegions.SOUTH,
    state: 'Mississippi',
    latitude: 32.7673,
    longitude: -89.6812,
  },
  {
    region: UnitedStatesRegions.WEST,
    state: 'Montana',
    latitude: 46.9048,
    longitude: -110.3261,
  },
  {
    region: UnitedStatesRegions.SOUTH,
    state: 'North Carolina',
    latitude: 35.6411,
    longitude: -79.8431,
  },
  {
    region: UnitedStatesRegions.MIDWEST,
    state: 'North Dakota',
    latitude: 47.5362,
    longitude: -99.793,
  },
  {
    region: UnitedStatesRegions.MIDWEST,
    state: 'Nebraska',
    latitude: 41.1289,
    longitude: -98.2883,
  },
  {
    region: UnitedStatesRegions.NORTHEAST,
    state: 'New Hampshire',
    latitude: 43.4108,
    longitude: -71.5653,
  },
  {
    region: UnitedStatesRegions.NORTHEAST,
    state: 'New Jersey',
    latitude: 40.314,
    longitude: -74.5089,
  },
  {
    region: UnitedStatesRegions.WEST,
    state: 'New Mexico',
    latitude: 34.8375,
    longitude: -106.2371,
  },
  {
    region: UnitedStatesRegions.WEST,
    state: 'Nevada',
    latitude: 38.4199,
    longitude: -117.1219,
  },
  {
    region: UnitedStatesRegions.NORTHEAST,
    state: 'New York',
    latitude: 42.1497,
    longitude: -74.9384,
  },
  {
    region: UnitedStatesRegions.MIDWEST,
    state: 'Ohio',
    latitude: 40.3736,
    longitude: -82.7755,
  },
  {
    region: UnitedStatesRegions.SOUTH,
    state: 'Oklahoma',
    latitude: 35.5376,
    longitude: -96.9247,
  },
  {
    region: UnitedStatesRegions.WEST,
    state: 'Oregon',
    latitude: 44.5672,
    longitude: -122.1269,
  },
  {
    region: UnitedStatesRegions.NORTHEAST,
    state: 'Pennsylvania',
    latitude: 40.5773,
    longitude: -77.264,
  },
  {
    region: UnitedStatesRegions.NORTHEAST,
    state: 'Rhode Island',
    latitude: 41.6772,
    longitude: -71.5101,
  },
  {
    region: UnitedStatesRegions.SOUTH,
    state: 'South Carolina',
    latitude: 33.8191,
    longitude: -80.9066,
  },
  {
    region: UnitedStatesRegions.MIDWEST,
    state: 'South Dakota',
    latitude: 44.2853,
    longitude: -99.4632,
  },
  {
    region: UnitedStatesRegions.SOUTH,
    state: 'Tennessee',
    latitude: 35.7449,
    longitude: -86.7489,
  },
  {
    region: UnitedStatesRegions.SOUTH,
    state: 'Texas',
    latitude: 31.106,
    longitude: -97.6475,
  },
  {
    region: UnitedStatesRegions.WEST,
    state: 'Utah',
    latitude: 40.1135,
    longitude: -111.8535,
  },
  {
    region: UnitedStatesRegions.SOUTH,
    state: 'Virginia',
    latitude: 37.768,
    longitude: -78.2057,
  },
  {
    region: UnitedStatesRegions.NORTHEAST,
    state: 'Vermont',
    latitude: 44.0407,
    longitude: -72.7093,
  },
  {
    region: UnitedStatesRegions.WEST,
    state: 'Washington',
    latitude: 47.3917,
    longitude: -121.5708,
  },
  {
    region: UnitedStatesRegions.MIDWEST,
    state: 'Wisconsin',
    latitude: 44.2563,
    longitude: -89.6385,
  },
  {
    region: UnitedStatesRegions.SOUTH,
    state: 'West Virginia',
    latitude: 38.468,
    longitude: -80.9696,
  },
  {
    region: UnitedStatesRegions.WEST,
    state: 'Wyoming',
    latitude: 42.7475,
    longitude: -107.2085,
  },
];
